Added Korean translation
preactjs/preact-www pull request #731
Opened 2021-01-04 13:26 UTC by helloworld-hellohyeon

Hello! Happy new year! 
I translated Preact Guide into Korean. 🇰🇷❤️
Special thanks to @x86chi and @verygooooood ❤️ (부족한 번역에 큰 도움을 주셔서 정말 감사합니다! 🥰)

2021-01-04 14:16 UTC, x86chi commented on content/kr/guide/v10/differences-to-react.md
> +Preact는 React를 재구현하기 위해 만들어진 것이 아니며 차이점이 있습니다. 이 차이점들의 대부분은 사소한 것들이거나 혹은, preact/compat를 사용해 완벽히 제거할 수 있습니다. [preact/compat]는 React와 100% 호환을 목표로 Preact 위에 덧씌우는 얉은 레이어입니다.
```suggestion
Preact는 React를 재구현하기 위한 것이 아닙니다. 차이점이 있습니다. 이 차이점들의 대부분은 사소한 것들이거나 혹은, preact/compat를 사용함으로써 완벽히 제거할 수 있습니다. [preact/compat]는 Preact 위에 덧씌우는 얇은 레이어로, React와의 100% 호환성을 목표로 합니다. 
```
> **Do not apply this line.** I used suggest change feature for showing diff from draft version.
>
> **실제로 반영하지 말아주세요.** 이전과 차이점을 보여드리기 위해 수정 제안을 썼습니다.

Wow. I've read front paragraph, its seems to be better then the draft version when you asked for correction :+1: I'll add more reviews tomorrow.

---

우와 앞 문단을 살짝 읽어보았는데 위 블럭 외에도 이전에 보여드린 초고보다 훨씬 자연스러워졌네요. 👍🏻 첨삭이 더 가능한지 더 살펴보고 싶지만 늦은 시간이라 내일 추가 리뷰를 달도록 하겠습니다.

혹시 이번 작업에 대해 공동 기여자를 명시해줄 수 있을까요?  조은님도 원한다면 넣는게 어떨까 싶네요. 이 커밋의 본문을 아래 텍스트로 수정하면 됩니다.

```
Co-authored-by: Muhun Kim <iam@muhun.kim>
```

> [Creating a commit with multiple authors - GitHub Docs](https://docs.github.com/en/free-pro-team@latest/github/committing-changes-to-your-project/creating-a-commit-with-multipleauthors#creating-co-authored-commits-on-the-command-line)

2021-01-04 14:24 UTC, helloworld-hellohyeon commented on content/kr/guide/v10/differences-to-react.md
> +Preact는 React를 재구현하기 위해 만들어진 것이 아니며 차이점이 있습니다. 이 차이점들의 대부분은 사소한 것들이거나 혹은, preact/compat를 사용해 완벽히 제거할 수 있습니다. [preact/compat]는 React와 100% 호환을 목표로 Preact 위에 덧씌우는 얉은 레이어입니다.
안녕하세요! 다시 한 번 확인해주셔서 감사합니다! 
내일 추가 리뷰를 종적으로 달아주시면 제가 다시 한 번 전체적으로 다듬어본 후 반영하는 커밋에서 공동 기여자를 명시하도록 하겠습니다. 감사합니다! 🥰

2021-01-05 01:09 UTC, verygooooood approved these changes
Looks good to me

2021-01-05 01:11 UTC, verygooooood commented
I don't know who is the owner of translation project at Preact.
I am GDE for web technologies and translate a lot of documents into Korean.
If the project need to Korean translation reviews, feel free to tag me.

Cheers 🍻

2021-01-05 12:31 UTC, mu-hun requested changes
참조하면 좋을 자료로 React 한국어 문서의 체크 리스트를 알려드립니다.
- [모범사례 확인 (Check best practices)](https://github.com/reactjs/ko.react.dev/blob/main/wiki/best-practices-for-translation.md)
- [용어 확인 (Check the term)](https://github.com/reactjs/ko.react.dev/blob/main/wiki/translate-glossary.md)

Link updated in <time datetime="2025-04-23">2025. 04. 23</time>

2021-01-05 12:31 UTC, x86chi commented on content/kr/guide/v10/differences-to-react.md
> +기존의 컴포넌트 라이브러리와의 원활한 통합을 위한 React 호환 `Children` API는 `preact/compat`에서 사용할 수 있습니다.
```suggestion
React와 호환되는 `Children` API는 `preact/compat`에서 제공되며 기존의 컴포넌트 라이브러리와 원활하게 통합할 수 있습니다.
```

> A React-compatible Children API is available from preact/compat to make integration with existing component libraries seamless.

2021-01-05 12:31 UTC, x86chi commented on content/kr/guide/v10/differences-to-react.md
> +### 특수한 목적의 컴포넌트
```suggestion
### 특수한 컴포넌트
```

조사 `의`를 지나치게 되는 것은 일본어의 영향입니다.

2021-01-05 12:31 UTC, x86chi commented on content/kr/guide/v10/differences-to-react.md
> +[preact/compat]는 모든 앱에서 필요하지는 않은 특수한 컴포넌트들도 포함하여 제공합니다.
```suggestion
[preact/compat]는 모든 앱에서 필요하지는 않은 특수한 컴포넌트를 포함해서 제공합니다.
```

2021-01-05 12:31 UTC, x86chi commented on content/kr/guide/v10/differences-to-react.md
> +- [forwardRef](/guide/v10/switching-to-preact#forwardRef): 명시된 자식 컴포넌트에 `ref`를 전달할 수 있습니다.
```suggestion
- [forwardRef](/guide/v10/switching-to-preact#forwardRef): 특정한 자식 컴포넌트에 `ref`를 전달할 수 있습니다.
```

> Supply a ref to a **specified** child component.

개인적 견해입니다.

2021-01-05 12:31 UTC, x86chi commented on content/kr/guide/v10/differences-to-react.md
> +- [lazy](/guide/v10/switching-to-preact#suspense): **실험 단계** 비동기 코드를 느리게(Lazy) 로드하고 트리를 준비됨/준비되지 않음 상태로 표시합니다.
```suggestion
- [lazy](/guide/v10/switching-to-preact#suspense): **실험 단계** 비동기 코드를 Lazy 로드하고 트리를 준비됨/준비되지 않음 상태로 표시합니다.
````

한국어로 명확히 정의된 용어가 없습니다. React 한국어 문서는 lazy 단어를 그대로 쓰고 있습니다.

> lazy 컴포넌트는 Suspense 컴포넌트 하위에서 렌더링되어야 하며, Suspense는 lazy 컴포넌트가 로드되길 기다리는 동안 로딩 화면과 같은 예비 컨텐츠를 보여줄 수 있게 해줍니다. — [React.lazy, 코드 분할 – React](https://ko.reactjs.org/docs/code-splitting.html#reactlazy)

2021-01-05 19:42 UTC, marvinhagemeister commented
This is amazing!! I don't speak Korean, so can't really review it. I see that there are some comments made here. If you feel like those are addressed, I'm more than happy to merge this 👍

2021-01-08 13:40 UTC, helloworld-hellohyeon commented on content/kr/guide/v10/differences-to-react.md
> +Preact는 React를 재구현하기 위해 만들어진 것이 아니며 차이점이 있습니다. 이 차이점들의 대부분은 사소한 것들이거나 혹은, preact/compat를 사용해 완벽히 제거할 수 있습니다. [preact/compat]는 React와 100% 호환을 목표로 Preact 위에 덧씌우는 얉은 레이어입니다.
안녕하세요! 일이 바빠서 제안해주신 수정사항을 오늘에서야 제대로 확인했습니다. 한 번에 묶어서 다시 커밋했고 바뀌지 않은 부분은 의역이라 그대로 뒀습니다! 한 번 더 검토 완료되시면 아래 달아주신 제안들 resolve 부탁드립니다! 따뜻한 주말 보내세요!

2021-01-08 16:18 UTC, ForsakenHarmony commented
> I don't know who is the owner of translation project at Preact.
> I am GDE for web technologies and translate a lot of documents into Korean.
> If the project need to Korean translation reviews, feel free to tag me.
> 
> Cheers 🍻

After this is merged (or with this PR) you could add yourself as a codeowner if you want to, thanks for taking the time

2021-01-09 08:12 UTC, x86chi requested changes
일반 사용자 권한으로 Resolve를 할 수 없네요. 대신 Outdate로 자동 마킹된 항목 대부분 괜찮다는 느낌을 받았습니다.

몇가지 오타를 발견해서 추가 요청을 드리고, 지난 리뷰에서 누락된 항목에 멘션을 걸었으니 확인 바랍니다.

2021-01-09 08:12 UTC, x86chi commented on content/kr/guide/v10/differences-to-react.md
> +레거시 `Context` API는 해당 값을 받기 위해 React의 `contextTypes`나 `childContextTypes`를 사용해 특정 속성을 선언해야 합니다. 하지만 Preact는 그럴 필요가 없습니다. 모든 Components들은 기본적으로 `getChildContext()`를 통해 만들어진 모든 `context` 속성들을 전달받습니다.
@helloworld-hellohyeon

2021-01-11 02:35 UTC, helloworld-hellohyeon commented
오타 수정했습니다! 변경된 건들은 제가 resolve 처리해둘게요.

2021-01-11 02:36 UTC, helloworld-hellohyeon commented on content/kr/guide/v10/differences-to-react.md
> +대게 역사적 이유로, 사실 React에서 `onChange` 이벤트의 의미는 모든 브라우저에서 지원하는 `onInput` 이벤트와 같습니다. `input` 이벤트는 폼 컨트롤이 수정되었을 때 반응할 주된 경우들에 있어 최적의 이벤트입니다. Preact core에서 `onChange`는 표준 [DOM 변경 이벤트](https://developer.mozil
😂😂

2021-01-11 05:03 UTC, x86chi approved these changes

2021-01-11 05:09 UTC, x86chi requested changes
커밋 이력과 upstream 저장소 간 병합은 변경 사항이 없으니 필요하지 않습니다. 
있어도 오픈소스 기여 시에 가능하면 rebase pull 을 권장드려요.

그래서 커밋 정리를 부탁드립니다.

2021-01-11 05:18 UTC, verygooooood commented
@x86chi 안녕하세요.
해당 rebase pull은 저장소에 따라서 다르기 때문에 
이 PR에서는 번역 퀄리티에 관한 건만 보는 것이 좋을 듯 합니다.

@ForsakenHarmony 
Thank you for reply! If possible, I will add me as code owner for Ko translation project.

2021-01-11 05:19 UTC, verygooooood approved these changes

2021-01-11 06:30 UTC, helloworld-hellohyeon commented
커밋 정리했습니다! rebase가 익숙하지 않아 좀 걸렸네요... 😢

2021-01-11 07:01 UTC, x86chi approved these changes

2021-01-11 09:03 UTC, marvinhagemeister approved these changes
Awesome, thank you so much for the translations 🙌

2021-01-11 09:03 UTC, merged