Update index.js
preactjs/preact-www pull request #842
Opened 2022-03-27 03:42 UTC by hmzisb

2022-04-05 13:12 UTC, binyamin requested changes

2022-04-05 13:12 UTC, binyamin commented on src/components/we-are-using/index.js
> +		name: 'BestForAndroid',
```suggestion
	},
	{
		name: 'BestForAndroid',
```

2022-04-05 13:12 UTC, binyamin commented on src/components/we-are-using/index.js
> +	}
Please place the image in the `src/assets/we-are-using/` folder.

2022-04-05 13:16 UTC, binyamin commented
@hmzisb This is a Wordpress site. What does this have to do with Preact?

2022-04-06 05:59 UTC, marvinhagemeister requested changes
I'm afraid we have to close this PR as the site contains links to circumvent licensing of android apps, which is not legal in many countries. That's not something we want to be associated with for legal reasons.

2022-04-06 06:01 UTC, closed without merging